פרק 5.2

In [2]:
# 🧠 הורדת קבצי dataset מ־GitHub (הרצה מתוך notebook עם !)
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz

--2026-04-27 09:19:14--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz [following]
--2026-04-27 09:19:14--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7725286 (7.4M) [application/octet-stream]
Saving to: ‘SQuAD_it-train.json.gz’

SQuAD_it-train.json 100%[===================>]   7.37M  --.-KB/s    in 0.09s

2026-04-27 09:19:15 (82.5 MB/s) - ‘SQuAD_it-train.json.gz’ saved [7725286/7725286]

--2026-04-27 09:19:15--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz [following]
--2026-04-27 09:19:15--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1051245 (1.0M) [application/octet-stream]
Saving to: ‘SQuAD_it-test.json.gz’

SQuAD_it-test.json. 100%[===================>]   1.00M  --.-KB/s    in 0.05s

2026-04-27 09:19:15 (19.6 MB/s) - ‘SQuAD_it-test.json.gz’ saved [1051245/1051245]

In [3]:
# 🧠 פתיחת קבצי gzip (המרה מ־.gz ל־.json)
!gzip -dkv SQuAD_it-*.json.gz

SQuAD_it-test.json.gz:	 87.5% -- created SQuAD_it-test.json
SQuAD_it-train.json.gz:	 82.3% -- created SQuAD_it-train.json

In [4]:
from datasets import load_dataset

# 🧠 טעינת dataset מקובץ JSON מקומי (לוקח רק את השדה "data")
squad_it_dataset = load_dataset(
    "json",
    data_files="SQuAD_it-train.json",
    field="data"
)

Generating train split: 0 examples [00:00, ? examples/s]

In [5]:
# 🧠 הצגת מבנה הדאטה (כמה שורות ואילו עמודות)
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
})

In [6]:
# 🧠 הצגת דוגמה אחת מהדאטה
squad_it_dataset["train"][0]

{'title': 'Terremoto del Sichuan del 2008',
 'paragraphs': [{'context': "Il terremoto del Sichuan del 2008 o il terremoto del Gran Sichuan, misurato a 8.0 Ms e 7.9 Mw, e si è verificato alle 02:28:01 PM China Standard Time all' epicentro (06:28:01 UTC) il 12 maggio nella provincia del Sichuan, ha ucciso 69.197 persone e lasciato 18.222 dispersi.",
   'qas': [{'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56cdca7862d2951400fa6826',
     'question': 'In quale anno si è verificato il terremoto nel Sichuan?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56cdca7862d2951400fa6828',
     'question': 'Quante persone sono state uccise come risultato?'},
    {'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56d4f9902ccc5a1400d833c0',
     'question': 'Quale anno ha avuto luogo il terremoto del Sichuan?'},
    {'answers': [{'answer_start': 78, 'text': '8.0 Ms e 7.9 Mw'}],
     'id': '56d4f9902ccc5a1400d833c1',
     'question': 'Che cosa ha fatto la misura di sisma?'},
    {'answers': [{'answer_start': 183, 'text': '12 maggio'}],
     'id': '56d4f9902ccc5a1400d833c2',
     'question': 'Che giorno si è verificato il terremoto?'},
    {'answers': [{'answer_start': 118,
       'text': '02:28:01 PM China Standard Time'}],
     'id': '56d4f9902ccc5a1400d833c3',
     'question': 'Che ora del giorno è accaduto il terremoto?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56d4f9902ccc5a1400d833c4',
     'question': 'Quante persone sono morte?'}]},
  {'context': 'E\' noto anche come terremoto di Wenchuan (Cinese:????; pinyin: Wènchu? n dà dìzhèn; letteralmente:"Grande terremoto di Wenchuan"), dopo l\' ubicazione dell\' epicentro del terremoto, Wenchuan County, Sichuan. L\' epicentro era di 80 chilometri (50 miglia) ad ovest nord-ovest di Chengdu, capoluogo di provincia, con una profondità focale di 19 km (12 miglia). Il terremoto ha colpito anche i paesi vicini e lontani da Pechino e Shanghai-1.500 km (930 mi) e 1.700 km (1.060 mi) di distanza, dove gli edifici adibiti a uffici hanno oscillato con il tremore. Forti scosse di assestamento, un po\' superiori alla magnitudo 6, hanno continuato a colpire l\' area anche mesi dopo il sisma principale, causando nuove vittime e danni.',
   'qas': [{'answers': [{'answer_start': 415, 'text': 'Pechino e Shanghai'}],
     'id': '56cdcb2c62d2951400fa6830',
     'question': 'Quali città lontane in altri paesi potrebbero sentire il terremoto?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56cdcb2c62d2951400fa6833',
     'question': 'Qual è stata la profondità focale del terremoto?'},
    {'answers': [{'answer_start': 659, 'text': 'mesi dopo'}],
     'id': '56cdcb2c62d2951400fa6834',
     'question': 'Quanto tempo dopo il terremoto si sono sentite le scosse di assestamento?'},
    {'answers': [{'answer_start': 181, 'text': 'Wenchuan County, Sichuan'}],
     'id': '56d4fb6f2ccc5a1400d833d5',
     'question': "Dov' era l' epicentro del terremoto?"},
    {'answers': [{'answer_start': 227, 'text': '80 chilometri'}],
     'id': '56d4fb6f2ccc5a1400d833d6',
     'question': 'Quanto lontano era da Chengdu?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56d4fb6f2ccc5a1400d833d7',
     'question': 'Qual era la profondità focale del sisma?'}]},
  {'context': "I dati ufficiali (al 21 luglio 2008 ore 12:00 CST) hanno dichiarato che 69.197 sono stati confermati morti, di cui 68.636 nella provincia del Sichuan e 374.176 feriti, di cui 18.222 scomparsi. Il terremoto ha lasciato circa 4,8 milioni di senzatetto, anche se il numero potrebbe raggiungere gli 11 milioni. Circa 15 milioni di persone vivevano nell' area colpita. E' stato il terremoto più mortale per colpire la Cina dopo il terremoto di Tangshan 1976, che ha ucciso almeno 240.000 persone, e il più forte del paese dal terremoto di Chayu 1950, che ha registrato a 8,5 sulla scala di magnitudo Richter. E' il 21° terremoto più morto di tutti i tempi. Il 6 novembre 2008, il governo centrale ha annunciato che avrebbe speso 1 trilione di RMB (circa 146,5 miliardi di dollari USA) nei prossimi tre anni per ricostruire le aree devastate dal terremoto, come parte del programma cinese di stimolo economico.",
   'qas': [{'answers': [{'answer_start': 72, 'text': '69.197'}],
     'id': '56cdcbb762d2951400fa683a',
     'question': 'Quante persone sono state confermate morte?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56cdcbb762d2951400fa683b',
     'question': 'Quanti morti sono stati confermati solo nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56cdcbb762d2951400fa683c',
     'question': 'Quante persone sono rimaste senza tetto a causa del terremoto?'},
    {'answers': [{'answer_start': 313, 'text': '15 milioni'}],
     'id': '56cdcbb762d2951400fa683d',
     'question': 'Quante persone hanno vissuto nella zona colpita?'},
    {'answers': [{'answer_start': 724, 'text': '1 trilione di RMB'}],
     'id': '56cdcbb762d2951400fa683e',
     'question': 'Quanto denaro è stato destinato alla ricostruzione di aree devastate?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56d4fca52ccc5a1400d833de',
     'question': 'Quante persone sono morte nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 152, 'text': '374.176'}],
     'id': '56d4fca52ccc5a1400d833df',
     'question': 'Quanti sono stati feriti nel Sichuan?'},
    {'answers': [{'answer_start': 175, 'text': '18.222'}],
     'id': '56d4fca52ccc5a1400d833e0',
     'question': 'Quante persone sono elencate come scomparse?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56d4fca52ccc5a1400d833e1',
     'question': 'Quante persone sono senzatetto a causa del terremoto?'},
    {'answers': [{'answer_start': 295, 'text': '11 milioni'}],
     'id': '56d4fca52ccc5a1400d833e2',
     'question': 'Quanto potrebbe arrivare il numero dei senzatetto?'}]},
  {'context': "Il terremoto ha avuto una magnitudine di 8,0 Ms e 7,9 Mw. L' epicentro è stato in Wenchuan County, Ngawa Tibetano e Prefettura Autonoma di Qiang, 80 km ad ovest / nord-ovest del capoluogo di provincia di Chengdu, con il suo tremore principale che si verifica alle 14:28:01.42 China Standard Time (06:28:01.42 UTC), il 12 maggio 2008 della durata di circa 2 minuti, nel terremoto quasi l' 80% degli edifici sono stati distrutti.",
   'qas': [{'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56cdcc5562d2951400fa6847',
     'question': 'Quanto tempo è durato il terremoto?'},
    {'answers': [{'answer_start': 388, 'text': '80%'}],
     'id': '56cdcc5562d2951400fa6848',
     'question': 'Quale percentuale di edifici è stata distrutta?'},
    {'answers': [{'answer_start': 41, 'text': '8,0 Ms e 7,9 Mw'}],
     'id': '56d4fe332ccc5a1400d833e8',
     'question': 'Qual era la magnitudo del terremoto?'},
    {'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56d4fe332ccc5a1400d833eb',
     'question': 'Quanto tempo è durato il tremore principale?'},
    {'answers': [{'answer_start': 379, 'text': "quasi l' 80%"}],
     'id': '56d4fe332ccc5a1400d833ec',
     'question': 'Quale percentuale di edifici è stata distrutta durante il sisma?'}]},
  {'context': "Secondo uno studio della China Earthquake Administration (CEA), il terremoto si è verificato lungo la faglia Longmenshan, una struttura di spinta lungo il confine della piastra Indo-Australiana e placca eurasiatica. Le attività sismiche si sono concentrate sulla sua frattura media (nota come frattura Yingxiu-Beichuan). La rottura è durata quasi 120 sec, con la maggior parte dell' energia rilasciata nei primi 80 sec. Partendo da Wenchuan, la rottura si propagò ad una velocità media di 3,1 chilometri al secondo 49° verso nord-est, rompendosi per un totale di circa 300 km. Lo spostamento massimo ammontava a 9 metri. Il fuoco era più profondo di 10 km.",
   'qas': [{'answers': [{'answer_start': 347, 'text': '120 sec'}],
     'id': '56cdccd962d2951400fa6850',
     'question': 'Quanto tempo ha durato la rottura?'},
    {'answers': [{'answer_start': 650, 'text': '10 km'}],
     'id': '56cdccd962d2951400fa6852',
     'question': 'Quanto è stato profondo il centro del terremoto?'},
    {'answers': [{'answer_start': 293, 'text': 'frattura Yingxiu-Beichuan'}],
     'id': '56d5005d2ccc5a1400d833f4',
     'question': 'Su quale frattura ha messo a fuoco il terremoto?'},
    {'answers': [{'answer_start': 612, 'text': '9 metri'}],
     'id': '56d5005d2ccc5a1400d833f6',
     'question': 'Qual è stato lo sfollamento più causato dal terremoto?'}]},
  {'context': 'Yazhou Zhoukan, con sede in Malesia, ha condotto un\' intervista con l\' ex ricercatore presso il China Seismological Bureau Geng Qingguo (??), in cui Geng ha sostenuto che un rapporto scritto riservato è stato inviato all\' Ufficio sismologico di Stato il 30 aprile 2008, avvertendo circa il possibile verificarsi di un terremoto significativo nella regione della prefettura di Ngawa del Sichuan intorno all\' 8 maggio, con una gamma di 10 giorni prima o dopo il terremoto. Il Geng, pur riconoscendo che la predizione del terremoto era ampiamente considerata problematica dalla comunità scientifica, credeva che "più grande è il terremoto, più facile è prevedere". Geng aveva a lungo tentato di stabilire una correlazione tra il verificarsi di siccità e terremoti; Premier Zhou Enlai ha riferito che ha preso interesse nel lavoro di Geng. La teoria di correlazione siccità-terra terremoto di Geng è stata pubblicata per la prima volta nel 1972, e ha detto di aver pronosticato con successo i terremoti di Haicheng 1975 e 1976 Tangshan. Lo stesso articolo di Yazhou Zhoukan ha sottolineato le difficoltà intrinseche associate alla previsione dei terremoti.',
   'qas': [{'answers': [{'answer_start': 936, 'text': '1972'}],
     'id': '56cdce0b62d2951400fa685b',
     'question': 'Quando è stata rilasciata la teoria di correlazione siccità-terra terremoto di Geng?'},
    {'answers': [{'answer_start': 394, 'text': "intorno all' 8 maggio"}],
     'id': '56d67a8d1c8504140094714f',
     'question': 'Qual era il tempo previsto per il terremoto?'},
    {'answers': [{'answer_start': 741, 'text': 'siccità'}],
     'id': '56d67a8d1c85041400947150',
     'question': 'Che cosa ha cercato Geng a lungo di stabilire come rapporto con i terremoti?'}]},
  {'context': 'In uno studio dell\' USGS (United States Geological Survey) i modelli preliminari di rottura del terremoto hanno indicato uno spostamento fino a 9 metri lungo un guasto lungo circa 240 km di lunghezza e 20 km di profondità. Il terremoto ha generato deformazioni della superficie superiori a 3 metri e ha aumentato lo stress (e la probabilità che si verifichino eventi futuri) alle estremità nord-orientale e sud-occidentale del guasto. Il 20 maggio, il sismologo dell\' USGS Tom Parsons ha avvertito che c\' è "alto rischio" di una grave scossa di assestamento M>7 nelle prossime settimane o mesi.',
   'qas': [{'answers': [{'answer_start': 137, 'text': 'fino a 9 metri'}],
     'id': '56cdcebe62d2951400fa6862',
     'question': 'Quanto è stato grande lo spostamento?'},
    {'answers': [{'answer_start': 473, 'text': 'Tom Parsons'}],
     'id': '56cdcebe62d2951400fa6866',
     'question': "Chi ha prima messo in guardia da possibili attività sismiche nell' area?"},
    {'answers': [{'answer_start': 144, 'text': '9 metri'}],
     'id': '56d5027a9d1b871400ae05e1',
     'question': "Che cosa ha mostrato il Geological Survey degli Stati Uniti come l' entità dello spostamento?"},
    {'answers': [{'answer_start': 202, 'text': '20 km di profondità'}],
     'id': '56d5027a9d1b871400ae05e3',
     'question': 'Quanto è profondo il guasto?'},
    {'answers': [{'answer_start': 508, 'text': 'alto rischio'}],
     'id': '56d5027a9d1b871400ae05e5',
     'question': 'Che cosa ha considerato Tom Parsons come il fattore di rischio per forti terremoti futuri?'}]},
  {'context': 'Sismologo giapponese Yuji Yagi Yuji Yagi presso l\' Università di Tsukuba ha detto che il terremoto si è verificato in due fasi:"Il 155 miglia Longmenshan Fault tore in due sezioni, il primo uno strappo di circa sette metri, seguita da un secondo che ha tosato quattro metri". I suoi dati hanno anche mostrato che il terremoto è durato circa due minuti e ha rilasciato 30 volte l\' energia del grande terremoto di Hanshin del 1995 in Giappone, che ha ucciso oltre 6.000 persone. Egli ha sottolineato che la scarsità dell\' epicentro e la densità di popolazione hanno notevolmente aumentato la gravità del terremoto. Teruyuki Kato, un sismologo dell\' Università di Tokyo, ha detto che le onde sismiche del terremoto hanno percorso una lunga distanza senza perdere il loro potere a causa della fermezza del terreno nella Cina centrale.',
   'qas': [{'answers': [{'answer_start': 115, 'text': 'in due fasi'}],
     'id': '56d504539d1b871400ae05eb',
     'question': 'Come ha fatto Yuji Yagi a dire che il terremoto è successo?'},
    {'answers': [{'answer_start': 142, 'text': 'Longmenshan Fault'}],
     'id': '56d504539d1b871400ae05ec',
     'question': 'Che errore si è verificato in due luoghi?'},
    {'answers': [{'answer_start': 368, 'text': '30 volte'}],
     'id': '56d504539d1b871400ae05ee',
     'question': 'Quanta più energia di quella prodotta dal terremoto del 1995 in Giappone?'},
    {'answers': [{'answer_start': 789, 'text': 'fermezza del terreno'}],
     'id': '56d504539d1b871400ae05ef',
     'question': 'Perché le onde sismiche hanno viaggiato finora?'}]},
  {'context': 'Tra 64 e 104 scosse di assestamento importanti, di magnitudo compresa tra 4,0 e 6,1, sono state registrate entro 72 ore dal sisma principale. Secondo i conteggi ufficiali cinesi,"alle ore 12:00 CST, 6 novembre 2008 c\' erano state 42.719 scariche post-shock totali, di cui 246 variavano da 4,0 SM a 4,9 SM, 34 da 5,0 MS a 5,9 MS, e 8 da 6,0 Ms a 6,4 MS; l\' urto post-shock più forte misurato 6,4 MS." L\' ultima scossa post-shock superiore a M6 si è verificato il 5 agosto.',
   'qas': [{'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56cdd08862d2951400fa6894',
     'question': 'Quante sono state le scosse di assestamento?'},
    {'answers': [{'answer_start': 107,
       'text': 'entro 72 ore dal sisma principale'}],
     'id': '56cdd08862d2951400fa6896',
     'question': 'Quando sono state registrate le scosse di assestamento?'},
    {'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56d505f99d1b871400ae05f5',
     'question': 'Quante sono state le scosse di assestamento entro 72 ore?'},
    {'answers': [{'answer_start': 230, 'text': '42.719'}],
     'id': '56d505f99d1b871400ae05f6',
     'question': 'Che cosa dicono i cinesi è il numero totale di shock dopo il terremoto?'},
    {'answers': [{'answer_start': 272, 'text': '246'}],
     'id': '56d505f99d1b871400ae05f8',
     'question': 'In quale data si sono verificate le scosse di assestamento più recenti superiori a 6 SM?'}]},
  {'context': '(Il terremoto della sig. ra 6.1 del 30 agosto 2008 nel Sichuan meridionale non faceva parte di questa serie perché è stato causato da una diversa colpa.',
   'qas': [{'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a0',
     'question': 'Dove si è verificato il terremoto?'},
    {'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a2',
     'question': "Dov' era il terremoto del 30 agosto 2008?"},
    {'answers': [{'answer_start': 20, 'text': 'sig'}],
     'id': '56d507269d1b871400ae05ff',
     'question': 'Qual era la grandezza del terremoto del Sichuan meridionale?'}]},
  {'context': 'La mappa dell\' intensità sismica pubblicata dal CEA dopo aver rilevato 500.000 km2 dell\' area colpita mostra una liedu massima di XI sulla scala di intensità sismica cinese (CSIS), descritta come "molto distruttiva" sulla scala macrosismica europea (EMS) da cui il CSIS ha tratto riferimento. (USGS, utilizzando la scala di intensità Mercalli modificata (CC), collocava anche l\' intensità massima a XI,"molto disastrosa". Due strisce sud-ovest-nord-est di liedu XI sono centrate intorno a Yingxiu, Wenchuan (la città più vicina all\' epicentro del terremoto principale) e Beichuan (la città ripetutamente colpita da forti scosse di assestamento tra cui una che registra MS 6.1 il 1 agosto 2008), entrambe nella provincia del Sichuan, occupando un totale di 2.419 km2. La zona Yingxiu liedu-XI è lunga circa 66 km e larga 20 km lungo Wenchuan-Dujiangyan-Pengzhou; la zona Beichuan liedu-XI è lunga circa 82 km e larga 15 km lungo An County-Beichuan-Pingwu. L\' area con liedu X (comparabile a X su EMS,"distruttivo" e X su MM,"disastroso") ha una superficie di 3.144 km2.',
   'qas': [{'answers': [{'answer_start': 48, 'text': 'CEA'}],
     'id': '56cdd21562d2951400fa68b0',
     'question': "Chi ha pubblicato la mappa dell' intensità dei terremoti?"},
    {'answers': [{'answer_start': 130, 'text': 'XI'}],
     'id': '56cdd21562d2951400fa68b2',
     'question': 'A quale intensità è stata scalata?'},
    {'answers': [{'answer_start': 489, 'text': 'Yingxiu, Wenchuan'}],
     'id': '56d5098a9d1b871400ae0609',
     'question': "Quale città era più vicina all' epicentro principale?"}]},
  {'context': "Il sistema Longmen Shan Fault System si trova al confine orientale dell' altopiano tibetano e contiene diversi difetti. Questo terremoto ha rotto almeno due strutture imbricate in Longmen Shan Fault System, vale a dire il Fault Beichuan e il Guanxian-Anxian Fault. Nell' area epicentrale, lo slittamento medio in Fault Beichuan era di circa 3,5 metri (11 ft) verticale, di 3,5 metri (11 ft) orizzontale parallelo al guasto, e di 4,8 metri (16 ft) orizzontale-pendicolare al guasto. Nell' area di circa 30 chilometri (19 miglia) a nord-est dell' epicentro, lo scivolamento superficiale su Beichuan Fault è stato quasi esclusivamente dextral strike-slip fino a circa 3 metri, mentre lo scivolamento medio in Guanxian-Anxian Fault è stato di circa 2 metri verticali (6 ft 7 in) e 2,3 metri (7 ft 7 in) orizzontali. il confine orientale dell' altopiano tibetano.",
   'qas': [{'answers': [{'answer_start': 665, 'text': '3 metri'}],
     'id': '56cdd4d762d2951400fa68cd',
     'question': 'Quanto è stato grande lo slip 30 km a nord-est del guasto?'},
    {'answers': [{'answer_start': 745, 'text': '2 metri'}],
     'id': '56cdd4d762d2951400fa68ce',
     'question': 'Qual è stato lo slittamento verticale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 777, 'text': '2,3 metri'}],
     'id': '56cdd4d762d2951400fa68cf',
     'question': 'Che cosa è stato lo slittamento orizzontale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 73, 'text': 'altopiano tibetano'}],
     'id': '56cdd4d762d2951400fa68d0',
     'question': 'Dove si trova il guasto dello shan Longmen?'},
    {'answers': [{'answer_start': 3,
       'text': 'sistema Longmen Shan Fault System'}],
     'id': '56d516439d1b871400ae0611',
     'question': 'Dove sono i guasti Beichuan e Guanxian-Ansia?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0612',
     'question': 'Qual è stato lo slittamento verticale medio nel difetto di Beichaun?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0613',
     'question': "Qual è stato lo slittamento orizzontale nel Fault Beichuan all' epicentro?"},
    {'answers': [{'answer_start': 429, 'text': '4,8 metri'}],
     'id': '56d516439d1b871400ae0614',
     'question': 'Qual è stato lo slittamento orizzontale perpendicolare al guasto?'}]},

In [7]:
# 🧠 טעינת train ו־test יחד כ־DatasetDict אחד
data_files = {
    "train": "SQuAD_it-train.json",
    "test": "SQuAD_it-test.json"
}

squad_it_dataset = load_dataset(
    "json",
    data_files=data_files,
    field="data"
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [8]:
# 🧠 טעינה ישירה מקבצי gzip בלי לפתוח אותם ידנית
data_files = {
    "train": "SQuAD_it-train.json.gz",
    "test": "SQuAD_it-test.json.gz"
}

squad_it_dataset = load_dataset(
    "json",
    data_files=data_files,
    field="data"
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [9]:
# 🧠 טעינת dataset מרחוק (ישירות מ־URL במקום קובץ מקומי)
url = "https://github.com/crux82/squad-it/raw/master/"

data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz"
}

squad_it_dataset = load_dataset(
    "json",
    data_files=data_files,
    field="data"
)

Downloading data:   0%|          | 0.00/7.73M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/1.05M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

פרק 5.3

In [18]:
# מורידים את קובץ הדאטה הדחוס מהאינטרנט
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"

# פותחים את קובץ ה-zip כדי לקבל את קבצי ה-TSV
!unzip drugsCom_raw.zip

--2026-04-27 09:32:54--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip.1’

drugsCom_raw.zip.1      [       <=>          ]  41.00M  19.8MB/s    in 2.1s

2026-04-27 09:32:57 (19.8 MB/s) - ‘drugsCom_raw.zip.1’ saved [42989872]

Archive:  drugsCom_raw.zip
replace drugsComTest_raw.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace drugsComTrain_raw.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [19]:
from datasets import load_dataset

# מגדירים איזה קובץ שייך ל-train ואיזה ל-test
data_files = {
    "train": "drugsComTrain_raw.tsv",
    "test": "drugsComTest_raw.tsv"
}

# טוענים קבצי TSV בעזרת loader של csv
# delimiter="\t" אומר שהעמודות מופרדות בטאב ולא בפסיק
drug_dataset = load_dataset(
    "csv",
    data_files=data_files,
    delimiter="\t"
)

In [20]:
# מערבבים את ה-train בצורה קבועה בעזרת seed
# ואז בוחרים 1000 דוגמאות ראשונות כדי לבדוק מדגם קטן
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))

# מציגים 3 דוגמאות ראשונות מהמדגם
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

In [21]:
# בודקים שהעמודה Unnamed: 0 היא מזהה ייחודי
# כלומר: מספר הערכים הייחודיים שווה למספר השורות בכל split
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

In [22]:
# משנים שם לעמודה Unnamed: 0 לשם ברור יותר: patient_id
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0",
    new_column_name="patient_id"
)

# מציגים את מבנה הדאטה אחרי שינוי השם
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [23]:
# פונקציה שממירה את condition לאותיות קטנות
def lowercase_condition(example):
    return {"condition": example["condition"].lower()}

# ניסיון להפעיל את הפונקציה על כל הדאטה
# זה עלול ליפול אם יש condition שהוא None
drug_dataset.map(lowercase_condition)

Map:   0%|          | 0/161297 [00:00<?, ? examples/s]

AttributeError: 'NoneType' object has no attribute 'lower'

In [24]:
# פונקציה שבודקת שה-condition לא ריק
def filter_nones(x):
    return x["condition"] is not None

In [25]:
# אותה פעולה כמו filter_nones, אבל בשורת lambda קצרה
# מסירים שורות שבהן condition הוא None
drug_dataset = drug_dataset.filter(
    lambda x: x["condition"] is not None
)

Filter:   0%|          | 0/161297 [00:00<?, ? examples/s]

Filter:   0%|          | 0/53766 [00:00<?, ? examples/s]

In [26]:
# עכשיו אחרי שהסרנו None, אפשר להמיר condition לאותיות קטנות
drug_dataset = drug_dataset.map(lowercase_condition)

# בדיקה שההמרה הצליחה
drug_dataset["train"]["condition"][:3]

Map:   0%|          | 0/160398 [00:00<?, ? examples/s]

Map:   0%|          | 0/53471 [00:00<?, ? examples/s]

['left ventricular dysfunction', 'adhd', 'birth control']

In [27]:
# פונקציה שסופרת כמה מילים יש בכל review
# היא מוסיפה עמודה חדשה בשם review_length
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

In [28]:
# מוסיפים לכל שורה עמודה חדשה: review_length
drug_dataset = drug_dataset.map(compute_review_length)

# מציגים דוגמה ראשונה כדי לראות שהעמודה נוספה
drug_dataset["train"][0]

Map:   0%|          | 0/160398 [00:00<?, ? examples/s]

Map:   0%|          | 0/53471 [00:00<?, ? examples/s]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

In [29]:
# ממיינים לפי review_length כדי לראות את הביקורות הכי קצרות
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

In [30]:
# מסירים ביקורות קצרות מדי
# נשאיר רק reviews עם יותר מ-30 מילים
drug_dataset = drug_dataset.filter(
    lambda x: x["review_length"] > 30
)

# מציגים כמה שורות נשארו בכל split
print(drug_dataset.num_rows)

Filter:   0%|          | 0/160398 [00:00<?, ? examples/s]

Filter:   0%|          | 0/53471 [00:00<?, ? examples/s]

{'train': 138514, 'test': 46108}

In [31]:
import html

# דוגמה לטקסט עם קידוד HTML
text = "I&#039;m a transformer called BERT"

# html.unescape מחזיר את התווים לצורה רגילה
html.unescape(text)

"I'm a transformer called BERT"

In [32]:
# גרסה מהירה יותר עם batched=True
# כאן x["review"] הוא list של טקסטים, ולכן משתמשים ב-list comprehension
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(o) for o in x["review"]]},
    batched=True
)

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

Map:   0%|          | 0/46108 [00:00<?, ? examples/s]

In [33]:
from transformers import AutoTokenizer

# טוענים tokenizer מהיר של BERT
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

# פונקציה שעושה tokenization לעמודת review
def tokenize_function(examples):
    return tokenizer(
        examples["review"],
        truncation=True
    )

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [79]:
# מודדים זמן להרצת tokenization על כל הדאטה עם batching
tokenized_dataset = drug_dataset.map(
    tokenize_function,
    batched=True
)

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

Map:   0%|          | 0/46108 [00:00<?, ? examples/s]

In [35]:
# טוענים tokenizer איטי לצורך השוואת ביצועים
slow_tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-cased",
    use_fast=False
)

# פונקציה שמשתמשת ב-tokenizer האיטי
def slow_tokenize_function(examples):
    return slow_tokenizer(
        examples["review"],
        truncation=True
    )

# מריצים tokenization עם batching ועם 8 תהליכים במקביל
tokenized_dataset = drug_dataset.map(
    slow_tokenize_function,
    batched=True,
    num_proc=8
)

Map (num_proc=8):   0%|          | 0/138514 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/46108 [00:00<?, ? examples/s]

In [36]:
# פונקציה שמפצלת טקסטים ארוכים לכמה chunks
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True
    )

In [37]:
# בודקים על דוגמה אחת כמה chunks יצאו
result = tokenize_and_split(drug_dataset["train"][0])

# מציגים את האורך של כל chunk
[len(inp) for inp in result["input_ids"]]

[128, 49]

In [80]:
# ניסיון להפעיל על כל הדאטה
# זה עלול לגרום לשגיאת mismatch כי טקסט אחד יכול להפוך לכמה דוגמאות
tokenized_dataset = drug_dataset.map(
    tokenize_and_split,
    batched=True
)

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

Map:   0%|          | 0/46108 [00:00<?, ? examples/s]

In [39]:
# פתרון פשוט ל-mismatch:
# מוחקים את העמודות המקוריות ומשאירים רק את הפלט החדש של tokenizer
tokenized_dataset = drug_dataset.map(
    tokenize_and_split,
    batched=True,
    remove_columns=drug_dataset["train"].column_names
)

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

Map:   0%|          | 0/46108 [00:00<?, ? examples/s]

In [40]:
# משווים בין מספר הדוגמאות אחרי הפיצול לבין הדאטה המקורי
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(212993, 138514)

In [41]:
# פתרון מתקדם:
# שומרים גם את העמודות המקוריות על ידי שכפול שלהן לפי ה-chunks החדשים
def tokenize_and_split(examples):
    result = tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True
    )

    # מיפוי: כל chunk חדש יודע מאיזו דוגמה מקורית הוא הגיע
    sample_map = result.pop("overflow_to_sample_mapping")

    # משכפלים את כל הערכים המקוריים לפי המיפוי
    for key, values in examples.items():
        result[key] = [values[i] for i in sample_map]

    return result

In [42]:
# עכשיו אפשר לפצל טקסטים ארוכים בלי למחוק את העמודות המקוריות
tokenized_dataset = drug_dataset.map(
    tokenize_and_split,
    batched=True
)

# מציגים את מבנה הדאטה החדש
tokenized_dataset

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

Map:   0%|          | 0/46108 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 212993
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 70952
    })
})

In [43]:
# משנים את פורמט הפלט ל-pandas
# עכשיו כשניגשים לדוגמאות נקבל DataFrame
drug_dataset.set_format("pandas")

In [44]:
# מציגים 3 שורות ראשונות כ-DataFrame
drug_dataset["train"][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89

In [81]:
train_df = drug_dataset["train"][:]

In [85]:
# מחשבים שכיחות של כל condition בעזרת Pandas
import pandas as pd
train_df = pd.DataFrame(drug_dataset["train"])
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "count": "frequency"})
)

# מציגים את הראשונות
frequencies.head()

       condition  frequency
0  birth control      27655
1     depression       8023
2           acne       5209
3        anxiety       4991
4           pain       4744

In [86]:
from datasets import Dataset

# מחזירים DataFrame ל-Dataset של Hugging Face
freq_dataset = Dataset.from_pandas(frequencies)

# מציגים את הדאטה החדש
freq_dataset

Dataset({
    features: ['condition', 'frequency'],
    num_rows: 819
})

In [48]:
# מחזירים את הפורמט הרגיל של datasets
# במקום pandas חוזרים ל-arrow/dict רגיל
drug_dataset.reset_format()

In [49]:
# יוצרים validation set מתוך train
# 80% נשאר train, ו-20% יהפוך ל-validation
drug_dataset_clean = drug_dataset["train"].train_test_split(
    train_size=0.8,
    seed=42
)

# ברירת המחדל קוראת לחלק השני "test"
# אנחנו משנים אותו ל-validation
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")

# מוסיפים את ה-test המקורי
drug_dataset_clean["test"] = drug_dataset["test"]

# מציגים את המבנה הסופי
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

In [50]:
# שומרים את הדאטה המנוקה לדיסק בפורמט Arrow
drug_dataset_clean.save_to_disk("drug-reviews")

Saving the dataset (0/1 shards):   0%|          | 0/110811 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/27703 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/46108 [00:00<?, ? examples/s]

In [51]:
from datasets import load_from_disk

# טוענים בחזרה dataset שנשמר בדיסק
drug_dataset_reloaded = load_from_disk("drug-reviews")

# מציגים את הדאטה שנטען
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

In [52]:
# שומרים כל split כקובץ JSONL נפרד
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format:   0%|          | 0/111 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/28 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/47 [00:00<?, ?ba/s]

In [53]:
# מציגים שורה אחת מקובץ ה-JSONL שנשמר
!head -n 1 drug-reviews-train.jsonl

{"patient_id":89879,"drugName":"Cyclosporine","condition":"keratoconjunctivitis sicca","review":"\"I have used Restasis for about a year now and have seen almost no progress.  For most of my life I&#039;ve had red and bothersome eyes. After trying various eye drops, my doctor recommended Restasis.  He said it typically takes 3 to 6 months for it to really kick in but it never did kick in.  When I put the drops in it burns my eyes for the first 30 - 40 minutes.  I&#039;ve talked with my doctor about this and he said it is normal but should go away after some time, but it hasn&#039;t. Every year around spring time my eyes get terrible irritated  and this year has been the same (maybe even worse than other years) even though I&#039;ve been using Restasis for a year now. The only difference I notice was for the first couple weeks, but now I&#039;m ready to move on.\"","rating":2.0,"date":"April 20, 2013","usefulCount":69,"review_length":147}

In [54]:
# טוענים מחדש את קבצי ה-JSONL ל-DatasetDict
data_files = {
    "train": "drug-reviews-train.jsonl",
    "validation": "drug-reviews-validation.jsonl",
    "test": "drug-reviews-test.jsonl",
}

drug_dataset_reloaded = load_dataset(
    "json",
    data_files=data_files
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

פרק 5.4

In [55]:
# מתקינים את zstandard כדי לפתוח קבצי .zst
!pip install zstandard

Requirement already satisfied: zstandard in /usr/local/lib/python3.12/dist-packages (0.25.0)

In [ ]:
from datasets import load_dataset

# טוענים את קובץ PubMed מהאינטרנט
data_files = "https://the-eye.eu/public/AI/pile_preliminary_components/PUBMED_title_abstracts_2019_baseline.jsonl.zst"
pubmed_dataset = load_dataset("json", data_files=data_files, split="train")
pubmed_dataset

In [ ]:
# מציגים את הדוגמה הראשונה
pubmed_dataset[0]

In [1]:
# מתקינים psutil למדידת RAM
!pip install psutil

Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (5.9.5)

In [2]:
import psutil

# מדפיסים כמה RAM התהליך משתמש
print(f"RAM used: {psutil.Process().memory_info().rss / (1024 * 1024):.2f} MB")

RAM used: 109.81 MB

In [ ]:
# מדפיסים את גודל הדאטה בדיסק
print(f"Dataset size in bytes: {pubmed_dataset.dataset_size}")
size_gb = pubmed_dataset.dataset_size / (1024**3)
print(f"Dataset size (cache file) : {size_gb:.2f} GB")

In [ ]:
import timeit

# מודדים כמה זמן לוקח לעבור על כל הדאטה
code_snippet = """batch_size = 1000

for idx in range(0, len(pubmed_dataset), batch_size):
    _ = pubmed_dataset[idx:idx + batch_size]
"""

time = timeit.timeit(stmt=code_snippet, number=1, globals=globals())
print(
    f"Iterated over {len(pubmed_dataset)} examples (about {size_gb:.1f} GB) in "
    f"{time:.1f}s, i.e. {size_gb/time:.3f} GB/s"
)

In [ ]:
# טוענים את אותו dataset במצב streaming
pubmed_dataset_streamed = load_dataset(
    "json", data_files=data_files, split="train", streaming=True
)

In [ ]:
# לוקחים דוגמה ראשונה מתוך ה-stream
next(iter(pubmed_dataset_streamed))

In [ ]:
from transformers import AutoTokenizer

# טוענים tokenizer ועושים tokenization תוך כדי streaming
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
tokenized_dataset = pubmed_dataset_streamed.map(lambda x: tokenizer(x["text"]))
next(iter(tokenized_dataset))

In [ ]:
# מערבבים את הדאטה עם buffer
shuffled_dataset = pubmed_dataset_streamed.shuffle(buffer_size=10_000, seed=42)
next(iter(shuffled_dataset))

In [ ]:
# לוקחים 5 דוגמאות ראשונות
dataset_head = pubmed_dataset_streamed.take(5)
list(dataset_head)

In [ ]:
# יוצרים train ו-validation מתוך הדאטה המעורבב
train_dataset = shuffled_dataset.skip(1000)
validation_dataset = shuffled_dataset.take(1000)

In [ ]:
# טוענים dataset נוסף במצב streaming
law_dataset_streamed = load_dataset(
    "json",
    data_files="https://the-eye.eu/public/AI/pile_preliminary_components/FreeLaw_Opinions.jsonl.zst",
    split="train",
    streaming=True,
)
next(iter(law_dataset_streamed))

In [ ]:
from itertools import islice
from datasets import interleave_datasets

# משלבים שני datasets יחד לסירוגין
combined_dataset = interleave_datasets([pubmed_dataset_streamed, law_dataset_streamed])
list(islice(combined_dataset, 2))

In [ ]:
# טוענים את כל The Pile במצב streaming
base_url = "https://the-eye.eu/public/AI/pile/"
data_files = {
    "train": [base_url + "train/" + f"{idx:02d}.jsonl.zst" for idx in range(30)],
    "validation": base_url + "val.jsonl.zst",
    "test": base_url + "test.jsonl.zst",
}
pile_dataset = load_dataset("json", data_files=data_files, streaming=True)
next(iter(pile_dataset["train"]))

פרק 5.5

In [ ]:
# מתקינים ספרייה לשליחת בקשות HTTP (ל־GitHub API)
!pip install requests

In [ ]:
import requests

# שולחים בקשת GET ל־GitHub API כדי לקבל issue אחד
url = "https://api.github.com/repos/huggingface/datasets/issues?page=1&per_page=1"
response = requests.get(url)

In [ ]:
# בודקים סטטוס הבקשה (200 = הצלחה)
response.status_code

In [ ]:
# מקבלים את התשובה בפורמט JSON
response.json()

In [ ]:
# מגדירים token לגישה ל־GitHub API (כדי להגדיל rate limit)
GITHUB_TOKEN = xxx  # Copy your GitHub token here
headers = {"Authorization": f"token {GITHUB_TOKEN}"}

In [ ]:
import time
import math
from pathlib import Path
import pandas as pd
from tqdm.notebook import tqdm

# פונקציה שמורידה issues מ־GitHub ושומרת כ־JSONL
def fetch_issues(
    owner="huggingface",
    repo="datasets",
    num_issues=10_000,
    rate_limit=5_000,
    issues_path=Path("."),
):
    if not issues_path.is_dir():
        issues_path.mkdir(exist_ok=True)

    batch = []
    all_issues = []
    per_page = 100  # מספר issues בכל בקשה
    num_pages = math.ceil(num_issues / per_page)
    base_url = "https://api.github.com/repos"

    for page in tqdm(range(num_pages)):
        # מביאים גם issues וגם pull requests
        query = f"issues?page={page}&per_page={per_page}&state=all"
        issues = requests.get(f"{base_url}/{owner}/{repo}/{query}", headers=headers)
        batch.extend(issues.json())

        # אם עברנו את ה־rate limit — מחכים שעה
        if len(batch) > rate_limit and len(all_issues) < num_issues:
            all_issues.extend(batch)
            batch = []
            print(f"Reached GitHub rate limit. Sleeping for one hour ...")
            time.sleep(60 * 60 + 1)

    all_issues.extend(batch)

    # ממירים ל־DataFrame
    df = pd.DataFrame.from_records(all_issues)

    # שומרים לקובץ JSONL
    df.to_json(f"{issues_path}/{repo}-issues.jsonl", orient="records", lines=True)

    print(
        f"Downloaded all the issues for {repo}! Dataset stored at {issues_path}/{repo}-issues.jsonl"
    )

In [ ]:
# מפעילים את הפונקציה כדי להוריד את כל ה־issues
fetch_issues()

In [ ]:
from datasets import load_dataset

# טוענים את הקובץ המקומי כ־Dataset
issues_dataset = load_dataset("json", data_files="datasets-issues.jsonl", split="train")
issues_dataset

In [ ]:
# לוקחים דגימה אקראית של 3 issues
sample = issues_dataset.shuffle(seed=666).select(range(3))

# מדפיסים URL והאם זה pull request
for url, pr in zip(sample["html_url"], sample["pull_request"]):
    print(f">> URL: {url}")
    print(f">> Pull request: {pr}\n")

In [ ]:
# מוסיפים עמודה חדשה שמסמנת אם זה pull request
issues_dataset = issues_dataset.map(
    lambda x: {"is_pull_request": False if x["pull_request"] is None else True}
)

In [ ]:
# בודקים תגובות (comments) ל־issue מסוים
issue_number = 2792
url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
response = requests.get(url, headers=headers)
response.json()

In [ ]:
# פונקציה שמחזירה את כל הטקסטים של התגובות ל־issue
def get_comments(issue_number):
    url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
    response = requests.get(url, headers=headers)
    return [r["body"] for r in response.json()]


# בדיקה על issue ספציפי
get_comments(2792)

In [ ]:
# מוסיפים עמודת comments לכל ה־dataset
issues_with_comments_dataset = issues_dataset.map(
    lambda x: {"comments": get_comments(x["number"])}
)

In [ ]:
from huggingface_hub import notebook_login

# התחברות ל־Hugging Face Hub
notebook_login()

In [ ]:
# # העלאת dataset ל־Hub
# issues_with_comments_dataset.push_to_hub("github-issues")

In [ ]:
# טעינת dataset מה־Hub
remote_dataset = load_dataset("lewtun/github-issues", split="train")
remote_dataset

פרק 5.6

In [1]:
# טוענים dataset של GitHub issues מה-Hub
from datasets import load_dataset

issues_dataset = load_dataset("lewtun/github-issues", split="train")
issues_dataset

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

datasets-issues-with-comments.jsonl:   0%|          | 0.00/12.2M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3019 [00:00<?, ? examples/s]

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason', 'pull_request', 'body', 'timeline_url', 'performed_via_github_app', 'is_pull_request'],
    num_rows: 3019
})

In [2]:
# מסננים רק issues (לא pull requests) ורק כאלה עם תגובות
issues_dataset = issues_dataset.filter(
    lambda x: (x["is_pull_request"] == False and len(x["comments"]) > 0)
)
issues_dataset

Filter:   0%|          | 0/3019 [00:00<?, ? examples/s]

Dataset({
    features: ['url', 'repository_url', 'labels_url', 'comments_url', 'events_url', 'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels', 'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments', 'created_at', 'updated_at', 'closed_at', 'author_association', 'active_lock_reason', 'pull_request', 'body', 'timeline_url', 'performed_via_github_app', 'is_pull_request'],
    num_rows: 808
})

In [3]:
# שומרים רק עמודות רלוונטיות לחיפוש
columns = issues_dataset.column_names
columns_to_keep = ["title", "body", "html_url", "comments"]
columns_to_remove = set(columns_to_keep).symmetric_difference(columns)

issues_dataset = issues_dataset.remove_columns(columns_to_remove)
issues_dataset

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 808
})

In [4]:
# עוברים לפורמט pandas כדי לעבוד עם explode
issues_dataset.set_format("pandas")
df = issues_dataset[:]

In [5]:
# מציגים את רשימת התגובות של שורה ראשונה
df["comments"][0].tolist()

['Cool, I think we can do both :)',
 '@lhoestq now the 2 are implemented.\r\n\r\nPlease note that for the the second protection, finally I have chosen to protect the master branch only from **merge commits** (see update comment above), so no need to disable/re-enable the protection on each release (direct commits, different from merge commits, can be pushed to the remote master branch; and eventually reverted without messing up the repo history).']

In [6]:
# מפצלים את עמודת comments כך שכל תגובה תהיה שורה נפרדת
comments_df = df.explode("comments", ignore_index=True)
comments_df.head(4)

,html_url,title,comments,body
0,https://github.com/huggingface/datasets/issues...,Protect master branch,"Cool, I think we can do both :)",After accidental merge commit (91c55355b634d0d...
1,https://github.com/huggingface/datasets/issues...,Protect master branch,@lhoestq now the 2 are implemented.\r\n\r\nPle...,After accidental merge commit (91c55355b634d0d...
2,https://github.com/huggingface/datasets/issues...,Backwards compatibility broken for cached data...,Hi ! I guess the caching mechanism should have...,## Describe the bug\r\nAfter upgrading to data...
3,https://github.com/huggingface/datasets/issues...,Backwards compatibility broken for cached data...,"If it's easy enough to implement, then yes ple...",## Describe the bug\r\nAfter upgrading to data...

In [7]:
# מחזירים ל-Dataset של Hugging Face
from datasets import Dataset

comments_dataset = Dataset.from_pandas(comments_df)
comments_dataset

Dataset({
    features: ['html_url', 'title', 'comments', 'body'],
    num_rows: 2964
})

In [8]:
# מוסיפים עמודה עם אורך כל תגובה (במילים)
comments_dataset = comments_dataset.map(
    lambda x: {"comment_length": len(x["comments"].split())}
)

Map:   0%|          | 0/2964 [00:00<?, ? examples/s]

In [9]:
# מסננים תגובות קצרות מדי
comments_dataset = comments_dataset.filter(lambda x: x["comment_length"] > 15)
comments_dataset

Filter:   0%|          | 0/2964 [00:00<?, ? examples/s]

Dataset({
    features: ['html_url', 'title', 'comments', 'body', 'comment_length'],
    num_rows: 2175
})

In [10]:
# פונקציה שמחברת title + body + comment לטקסט אחד
def concatenate_text(examples):
    return {
        "text": examples["title"]
        + " \n "
        + examples["body"]
        + " \n "
        + examples["comments"]
    }

comments_dataset = comments_dataset.map(concatenate_text)

Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [11]:
# טוענים מודל ו-tokenizer ליצירת embeddings
from transformers import AutoTokenizer, AutoModel

model_ckpt = "sentence-transformers/multi-qa-mpnet-base-dot-v1"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
model = AutoModel.from_pretrained(model_ckpt)

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/multi-qa-mpnet-base-dot-v1
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [12]:
# מעבירים את המודל ל-GPU
import torch

device = torch.device("cuda")
model.to(device)

MPNetModel(
  (embeddings): MPNetEmbeddings(
    (word_embeddings): Embedding(30527, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): MPNetEncoder(
    (layer): ModuleList(
      (0-11): 12 x MPNetLayer(
        (attention): MPNetAttention(
          (attn): MPNetSelfAttention(
            (q): Linear(in_features=768, out_features=768, bias=True)
            (k): Linear(in_features=768, out_features=768, bias=True)
            (v): Linear(in_features=768, out_features=768, bias=True)
            (o): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (intermediate): MPNetIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): MPNetOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (relative_attention_bias): Embedding(32, 12)
  )
  (pooler): MPNetPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [13]:
# פונקציה שלוקחת את ה-[CLS] token כייצוג המשפט
def cls_pooling(model_output):
    return model_output.last_hidden_state[:, 0]

In [14]:
# פונקציה שמייצרת embeddings לטקסטים
def get_embeddings(text_list):
    encoded_input = tokenizer(
        text_list, padding=True, truncation=True, return_tensors="pt"
    )
    encoded_input = {k: v.to(device) for k, v in encoded_input.items()}
    model_output = model(**encoded_input)
    return cls_pooling(model_output)

In [15]:
# בדיקה: יוצרים embedding לטקסט אחד
embedding = get_embeddings(comments_dataset["text"][0])
embedding.shape

torch.Size([1, 768])

In [16]:
# מוסיפים עמודת embeddings לכל הדאטה
embeddings_dataset = comments_dataset.map(
    lambda x: {"embeddings": get_embeddings(x["text"]).detach().cpu().numpy()[0]}
)

Map:   0%|          | 0/2175 [00:00<?, ? examples/s]

In [26]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.1)
Downloading faiss_cpu-1.13.2-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 79.4 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.13.2

In [29]:
import faiss
print(faiss.__version__)

1.13.2

In [30]:
# יוצרים אינדקס FAISS על embeddings
embeddings_dataset.add_faiss_index(column="embeddings")

ImportError: You must install Faiss to use FaissIndex. To do so you can run `conda install -c pytorch faiss-cpu` or `conda install -c pytorch faiss-gpu`. A community supported package is also available on pypi: `pip install faiss-cpu` or `pip install faiss-gpu`. Note that pip may not have the latest version of FAISS, and thus, some of the latest features and bug fixes may not be available.

In [ ]:
# מחפשים את התוצאות הכי דומות לשאלה
scores, samples = embeddings_dataset.get_nearest_examples(
    "embeddings", question_embedding, k=5
)

In [ ]:
# מציגים את התוצאות בצורה נוחה עם pandas
import pandas as pd

samples_df = pd.DataFrame.from_dict(samples)
samples_df["scores"] = scores
samples_df.sort_values("scores", ascending=False, inplace=True)

In [ ]:
# מדפיסים את התוצאות (תגובות + ציון + כותרת + קישור)
for _, row in samples_df.iterrows():
    print(f"COMMENT: {row.comments}")
    print(f"SCORE: {row.scores}")
    print(f"TITLE: {row.title}")
    print(f"URL: {row.html_url}")
    print("=" * 50)
    print()